config/routes.rb
BookApp::Application.routes.draw do
  resources :business_websites

  resources :orders

  resources :books

  resources :publishers

  resources :customers

end

app/models/publisher.rb
# == Schema Information
#
# Table name: publishers
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  city       :string(255)
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

class Publisher < ActiveRecord::Base
  has_many :books
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  # GET /publishers
  # GET /publishers.json
  def index
    @publishers = Publisher.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @publishers }
    end
  end

  # GET /publishers/1
  # GET /publishers/1.json
  def show
    @publisher = Publisher.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @publisher }
    end
  end

  # GET /publishers/new
  # GET /publishers/new.json
  def new
    @publisher = Publisher.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @publisher }
    end
  end

  # GET /publishers/1/edit
  def edit
    @publisher = Publisher.find(params[:id])
  end

  # POST /publishers
  # POST /publishers.json
  def create
    @publisher = Publisher.new(params[:publisher])

    respond_to do |format|
      if @publisher.save
        format.html { redirect_to @publisher, notice: 'Publisher was successfully created.' }
        format.json { render json: @publisher, status: :created, location: @publisher }
      else
        format.html { render action: "new" }
        format.json { render json: @publisher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /publishers/1
  # PUT /publishers/1.json
  def update
    @publisher = Publisher.find(params[:id])

    respond_to do |format|
      if @publisher.update_attributes(params[:publisher])
        format.html { redirect_to @publisher, notice: 'Publisher was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @publisher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publishers/1
  # DELETE /publishers/1.json
  def destroy
    @publisher = Publisher.find(params[:id])
    @publisher.destroy

    respond_to do |format|
      format.html { redirect_to publishers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/views/publishers/_form.html.erb
<%= semantic_form_for @publisher do |f| %>
  <%= f.inputs do %>
    <%= f.input :name %>
    <%= f.input :city %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :input %>
  <% end %>
<% end %>

app/views/publishers/edit.html.erb
<h1>Editing publisher</h1>

<%= render 'form' %>

<%= link_to 'Show', @publisher %> |
<%= link_to 'Back', publishers_path %>

app/views/publishers/index.html.erb
<h1>Listing publishers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>City</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @publishers.each do |publisher| %>
  <tr>
    <td><%= publisher.name %></td>
    <td><%= publisher.city %></td>
    <td><%= link_to 'Show', publisher %></td>
    <td><%= link_to 'Edit', edit_publisher_path(publisher) %></td>
    <td><%= link_to 'Destroy', publisher, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Publisher', new_publisher_path %>

app/views/publishers/new.html.erb
<h1>New publisher</h1>

<%= render 'form' %>

<%= link_to 'Back', publishers_path %>

app/views/publishers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @publisher.name %>
</p>

<p>
  <b>City:</b>
  <%= @publisher.city %>
</p>


<%= link_to 'Edit', edit_publisher_path(@publisher) %> |
<%= link_to 'Back', publishers_path %>