config/routes.rb
BookApp::Application.routes.draw do
  resources :business_websites

  resources :orders

  resources :books

  resources :publishers

  resources :customers

end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id           :integer         not null, primary key
#  payment_type :string(255)
#  card         :string(255)
#  date         :date
#  status       :string(255)
#  customer_id  :integer
#  created_at   :datetime        not null
#  updated_at   :datetime        not null
#

class Order < ActiveRecord::Base
  belongs_to :customer
  has_many :books, :through => :contains
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orders }
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order = Order.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/new
  # GET /orders/new.json
  def new
    @order = Order.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/1/edit
  def edit
    @order = Order.find(params[:id])
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(params[:order])

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render json: @order, status: :created, location: @order }
      else
        format.html { render action: "new" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /orders/1
  # PUT /orders/1.json
  def update
    @order = Order.find(params[:id])

    respond_to do |format|
      if @order.update_attributes(params[:order])
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= semantic_form_for @order do |f| %>
  <%= f.inputs do %>
    <%= f.input :payment_type %>
    <%= f.input :card %>
    <%= f.input :date %>
    <%= f.input :status %>
    <%= f.input :customer %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :input %>
  <% end %>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>Listing orders</h1>

<table>
  <tr>
    <th>Payment type</th>
    <th>Card</th>
    <th>Date</th>
    <th>Status</th>
    <th>Customer</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @orders.each do |order| %>
  <tr>
    <td><%= order.payment_type %></td>
    <td><%= order.card %></td>
    <td><%= order.date %></td>
    <td><%= order.status %></td>
    <td><%= order.customer %></td>
    <td><%= link_to 'Show', order %></td>
    <td><%= link_to 'Edit', edit_order_path(order) %></td>
    <td><%= link_to 'Destroy', order, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Payment type:</b>
  <%= @order.payment_type %>
</p>

<p>
  <b>Card:</b>
  <%= @order.card %>
</p>

<p>
  <b>Date:</b>
  <%= @order.date %>
</p>

<p>
  <b>Status:</b>
  <%= @order.status %>
</p>

<p>
  <b>Customer:</b>
  <%= @order.customer %>
</p>


<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>