config/routes.rb
BookApp::Application.routes.draw do
  resources :business_websites

  resources :orders

  resources :books

  resources :publishers

  resources :customers

end

app/models/business_website.rb
class BusinessWebsite < ActiveRecord::Base
end

app/controllers/business_websites_controller.rb
class BusinessWebsitesController < ApplicationController
  # GET /business_websites
  # GET /business_websites.json
  def index
    @business_websites = BusinessWebsite.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @business_websites }
    end
  end

  # GET /business_websites/1
  # GET /business_websites/1.json
  def show
    @business_website = BusinessWebsite.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @business_website }
    end
  end

  # GET /business_websites/new
  # GET /business_websites/new.json
  def new
    @business_website = BusinessWebsite.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @business_website }
    end
  end

  # GET /business_websites/1/edit
  def edit
    @business_website = BusinessWebsite.find(params[:id])
  end

  # POST /business_websites
  # POST /business_websites.json
  def create
    @business_website = BusinessWebsite.new(params[:business_website])

    respond_to do |format|
      if @business_website.save
        format.html { redirect_to @business_website, notice: 'Business website was successfully created.' }
        format.json { render json: @business_website, status: :created, location: @business_website }
      else
        format.html { render action: "new" }
        format.json { render json: @business_website.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /business_websites/1
  # PUT /business_websites/1.json
  def update
    @business_website = BusinessWebsite.find(params[:id])

    respond_to do |format|
      if @business_website.update_attributes(params[:business_website])
        format.html { redirect_to @business_website, notice: 'Business website was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @business_website.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /business_websites/1
  # DELETE /business_websites/1.json
  def destroy
    @business_website = BusinessWebsite.find(params[:id])
    @business_website.destroy

    respond_to do |format|
      format.html { redirect_to business_websites_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/business_websites_helper.rb
module BusinessWebsitesHelper
end

app/views/business_websites/_form.html.erb
<%= semantic_form_for @business_website do |f| %>
  <%= f.inputs do %>
    <%= f.input :domain_name %>
    <%= f.input :domain_suffix %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :input %>
  <% end %>
<% end %>

app/views/business_websites/edit.html.erb
<h1>Editing business_website</h1>

<%= render 'form' %>

<%= link_to 'Show', @business_website %> |
<%= link_to 'Back', business_websites_path %>

app/views/business_websites/index.html.erb
<h1>Listing business_websites</h1>

<table>
  <tr>
    <th>Domain name</th>
    <th>Domain suffix</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @business_websites.each do |business_website| %>
  <tr>
    <td><%= business_website.domain_name %></td>
    <td><%= business_website.domain_suffix %></td>
    <td><%= link_to 'Show', business_website %></td>
    <td><%= link_to 'Edit', edit_business_website_path(business_website) %></td>
    <td><%= link_to 'Destroy', business_website, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Business website', new_business_website_path %>

app/views/business_websites/new.html.erb
<h1>New business_website</h1>

<%= render 'form' %>

<%= link_to 'Back', business_websites_path %>

app/views/business_websites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Domain name:</b>
  <%= @business_website.domain_name %>
</p>

<p>
  <b>Domain suffix:</b>
  <%= @business_website.domain_suffix %>
</p>


<%= link_to 'Edit', edit_business_website_path(@business_website) %> |
<%= link_to 'Back', business_websites_path %>